import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";
import { FcGoogle } from "react-icons/fc";
import { InferGetServerSidePropsType } from "next";
import Image from "next/image";
import { CtxOrReq } from "next-auth/client/_utils";
import {useRouter} from "next/router";
import logo from "../../../public/logo.svg"
const SignIn = ({
  providers,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  console.log(providers);
    const router = useRouter()

  return (
    <div className="grid h-screen place-items-center py-12 px-4 sm:px-6 lg:px-8">
      <Head>
        <title>Hizitickets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-md space-y-8">
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
            Sign in to your account
          </h2>
          <div className="justify-center flex ">
            {providers
              ? Object.values(providers).map((provider) => (
                  <div key={provider.name}>
                    <button className="btn gap-2 bg-accent"
                      onClick={() => signIn(provider.id,{ callbackUrl: router?.query?.callbackUrl?.toString() })}
                    >
                    <FcGoogle/>
                      Sign in with {provider.name}
                    </button>
                  </div>
                ))
              : ""}
          </div>
      </div>
    </div>
  );
};
export const getServerSideProps = async (context: CtxOrReq | undefined) => {

  const providers = await getProviders();
  return {
    props: { providers },
  };
};

export default SignIn;
