
import { type NextPage } from "next";
import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";
import { FcGoogle } from "react-icons/fc";
import { InferGetServerSidePropsType } from "next";

import { CtxOrReq } from "next-auth/client/_utils";

const SignIn = ({
  providers,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className="grid h-screen w-full grid-cols-2 bg-[url('../../public/background1.svg')]">
      <Head>
        <title>Hizitickets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="col-end-3 m-6 grid w-full place-items-center rounded-lg bg-white">
        <div>
          <h1 className="m-2 text-xl font-bold text-[#43425D]">NEWWEL MUSIC</h1>
          <h2 className="m-2 text-[#43425D]">
            Welcome back! Please login to your account
          </h2>
        </div>

        {providers
          ? Object.values(providers).map((provider) => (
              <div key={provider.name}>
                    <button className="btn gap-2 bg-accent"
                      onClick={() => signIn(provider.id)}
                    >
                    <FcGoogle/>
                      Sign in with {provider.name}
                    </button>
              </div>
            ))
          : ""}
      </div>
    </div>
  );
};
export const getServerSideProps = async (context: CtxOrReq | undefined) => {
  const providers = await getProviders();
  return {
    props: { providers },
  };
};
export default SignIn;


