import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import background from "../../public/background.svg";
const Home: NextPage = () => {
  const router = useRouter();
  /*useEffect(() => {
    const token = localStorage.getItem("visited");
    if (token) {
      router.push("/events");
    } else {
      localStorage.setItem("visited", "true");
    }
  }, []);*/
  return (
    <>
      <div data-theme="light">
        <Head>
          <title>Hizitickets</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <input type="checkbox" id="my-modal-3" className="modal-toggle" />
        <div className="modal">
          <div className="modal-box">
            <label
              htmlFor="my-modal-3"
              className="btn btn-sm btn-circle absolute right-2 top-2"
            >
              ✕
            </label>
            <h3 className="font-bold text-lg">
              Start Your experience right now!
            </h3>

            <div className="modal-action">
              <label
                htmlFor="my-modal-3"
                className="btn btn-outline"
                onClick={() => {
                  router.push("/events");
                }}
              >
                View events
              </label>
              <label
                htmlFor="my-modal-3"
                className="btn btn-outline"
                onClick={() => {
                  router.push("/dashboard");
                }}
              >
                Create your event
              </label>
            </div>
          </div>
        </div>
        <section className="bg-gray-50">
          <div className=" bg-[url('../../public/background.svg')] mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center">
            <div className="mx-auto max-w-xl text-center bg-white">
              <h1 className="text-3xl m-2 font-extrabold sm:text-5xl">
                We understand your ticketing needs.
                <strong className="font-extrabold m-2 text-accent sm:block">
                  Welcome to Hizitickets.
                </strong>
              </h1>

              <p className="mt-4 sm:text-xl sm:leading-relaxed">
                Home of fast, convinient and simple ticketing
              </p>

              <div className="mt-8 flex flex-wrap justify-center gap-4">
                <label
                  htmlFor="my-modal-3"
                  className="btn modal-button block w-full rounded bg-accent px-12 py-3 text-sm font-medium text-white shadow hover:bg-gray-500 focus:outline-none focus:ring active:bg-red-500 sm:w-auto"
                >
                  Get Started
                </label>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default Home;
