import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../public/logo.svg"
const Home: NextPage = () => {
  const router = useRouter();
  /*useEffect(() => {
    const token = localStorage.getItem("visited");
    if (token) {
      router.push("/events");
    } else {
      localStorage.setItem("visited", "true");
    }
  }, []);*/
  return (
    <>
      <div className="bg-gray-50 h-screen" data-theme="corporate">
        <Head>
          <title>Hizitickets</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <input type="checkbox" id="my-modal-3" className="modal-toggle" />
        <div className="modal">
          <div className="modal-box">
            <label
              htmlFor="my-modal-3"
              className="btn btn-sm btn-accent  btn-circle absolute right-2 top-2"
            >
              ✕
            </label>
            <h3 className="font-bold text-lg">
              Start Your experience right now!
            </h3>

            <div className="modal-action">
              <label
                htmlFor="my-modal-3"
                className="btn btn-accent hover:btn-accent-focus text-accent-content"
                onClick={() => {
                  router.push("/events");
                }}
              >
                View events
              </label>
              <label
                htmlFor="my-modal-3"
                className="btn btn-accent hover:btn-accent-focus text-accent-content"
                onClick={() => {
                  router.push("/dashboard");
                }}
              >
                Create your event
              </label>
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-between max-w-xl px-4 mx-auto lg:pt-16 lg:flex-row md:px-8 lg:max-w-screen-xl">
          <div className="pt-16 mb-16 lg:mb-0 lg:pt-32 lg:max-w-lg lg:pr-5">
            <div className="max-w-xl mb-6">
              <div>
                <p className="inline-block px-3 py-px mb-4 text-xs font-semibold tracking-wider text-teal-900 uppercase rounded-full bg-teal-accent-400">
                  What&apos;s new?
                </p>
              </div>
              <h2 className="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                We understand
                <br className="hidden md:block" />
                {' '}
                <span className="inline-block text-deep-purple-accent-400">
                  your ticketing needs.
                </span>
              </h2>
              <p className="text-base text-gray-700 md:text-lg">
                Welcome to Hizitickets.
              </p>
            </div>
            <div className="flex items-center">
              <label
                htmlFor="my-modal-3"
                className="inline-flex btn-accent items-center justify-center h-12 px-6 mr-6 font-medium tracking-wide text-accent-content transition duration-200 rounded shadow-md  hover:btn-accent-focus focus:shadow-outline focus:outline-none"
              >
                Get started
              </label>

            </div>
          </div>
          <div>
            <div className="mockup-phone">
              <div className="camera"></div>
              <div className="display">
                <div className="artboard artboard-demo phone-1">
                  <Image src={logo} alt="hizitickets" />

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
