import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import logo from "../../public/logo.svg";
const Home: NextPage = () => {
  const router = useRouter();
  /*useEffect(() => {
    const token = localStorage.getItem("visited");
    if (token) {
      router.push("/events");
    } else {
      localStorage.setItem("visited", "true");
    }
  }, []);*/
  return (
    <>
      <div className="h-screen bg-gray-50" data-theme="corporate">
        <Head>
          <title>Hizitickets</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <input type="checkbox" id="my-modal-3" className="modal-toggle" />
        <div className="modal">
          <div className="modal-box">
            <label
              htmlFor="my-modal-3"
              className="btn-accent btn-sm btn-circle  btn absolute right-2 top-2"
            >
              ✕
            </label>
            <h3 className="text-lg font-bold">
              Start Your experience right now!
            </h3>

            <div className="modal-action">
              <label
                htmlFor="my-modal-3"
                className="hover:btn-accent-focus btn-accent btn text-accent-content"
                onClick={() => {
                  router.push("/events");
                }}
              >
                View events
              </label>
              <label
                htmlFor="my-modal-3"
                className="hover:btn-accent-focus btn-accent btn text-accent-content"
                onClick={() => {
                  router.push("/dashboard");
                }}
              >
                Create your event
              </label>
            </div>
          </div>
        </div>
        <div className="mx-auto flex max-w-xl flex-col justify-between px-4 md:px-8 lg:max-w-screen-xl lg:flex-row lg:pt-16">
          <div className="mb-16 pt-16 lg:mb-0 lg:max-w-lg lg:pt-32 lg:pr-5">
            <div className="mb-6 max-w-xl">
              <div>
                <p className="bg-teal-accent-400 mb-4 inline-block rounded-full px-3 py-px text-xs font-semibold uppercase tracking-wider text-teal-900">
                  What&apos;s new?
                </p>
              </div>
              <h2 className="mb-6 max-w-lg font-sans text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl sm:leading-none">
                We understand
                <br className="hidden md:block" />{" "}
                <span className="text-deep-purple-accent-400 inline-block">
                  your ticketing needs.
                </span>
              </h2>
              <p className="text-base text-gray-700 md:text-lg">
                Welcome to Hizitickets.
              </p>
            </div>
            <div className="flex items-center">
              <label
                htmlFor="my-modal-3"
                className="hover:bg-teal-700 focus:shadow-outline bg-teal-600 mr-6 inline-flex h-12 items-center justify-center rounded px-6 font-medium tracking-wide text-white shadow-md  transition duration-200 focus:outline-none"
              >
                Get started
              </label>
            </div>
          </div>
          <div>
            <div className="mockup-phone">
              <div className="camera"></div>
              <div className="display">
                <div className="phone-1 artboard artboard-demo">
                  <Image src={logo} alt="hizitickets" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
