import { useSession, signOut } from "next-auth/react";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import logo from "../../public/logo.svg";
export default function Nav() {
  const [isDashboard, setIsDashboard] = useState<boolean>(false);
  const { data: session, status } = useSession();

  const router = useRouter();
  useEffect(() => {
    if (router.pathname == "/dashboard") {
      setIsDashboard(true);
    }
  }, []);
  return (
    <>
      <div className="navbar bg-base-100">
        <Head>
          <title>Hizitickets</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="navbar-start">
          <div className="dropdown">
            <label tabIndex={0} className="btn-ghost btn lg:hidden">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h8m-8 6h16"
                />
              </svg>
            </label>
            <ul
              tabIndex={0}
              className="dropdown-content menu rounded-box menu-compact mt-3 w-52 bg-base-100 p-2 shadow"
            >
              <li>
                <Link className="btn-ghost btn text-primary" href="/events">
                  Events
                </Link>
              </li>
              <li>
                <Link className="btn-ghost btn text-primary" href="/dashboard">
                  Dashboard
                </Link>
              </li>
              <li>
                <Link className="btn-ghost btn text-primary" href="/help">
                  Get Help
                </Link>
              </li>
            </ul>
          </div>
          <Link href="/events" className="btn-ghost btn text-xl normal-case">
            <Image src={logo} alt="hizitickets" />
          </Link>
        </div>
        <div className="navbar-center hidden lg:flex">
          <ul className="menu menu-horizontal p-0">
            <li>
              <Link className="btn-ghost btn text-primary" href="/dashboard">
                Dashboard
              </Link>
            </li>
            <li>
              <Link className="btn-ghost btn text-primary" href="/events">
                Events
              </Link>
            </li>
            <li>
              <Link className="btn-ghost btn text-primary" href="/help">
                Get Help
              </Link>
            </li>
          </ul>
        </div>
        <div className="navbar-end">
          {isDashboard && (
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn-ghost btn-circle avatar btn">
                <div className="w-10 rounded-full">
                  <img src={`${session?.user?.image} `} alt="profile image" />
                </div>
              </label>
              <ul
                tabIndex={0}
                className="dropdown-content menu rounded-box menu-compact mt-3 w-52 bg-base-100 p-2 shadow"
              >
                <li>
                  <a
                    onClick={() => {
                      signOut();
                    }}
                  >
                    Logout
                  </a>
                </li>
              </ul>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
